spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-api?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update #cuidado!
    show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: false
